package:
    type:           composer-plugin
    name:           composer-extension-plugin
    title:          Composer plugin for pluggable extensions
    headline:       Composer Extension Plugin
    keywords:       composer, pluggable, extension, plugin
    namespace:      hiqdev\composerextensionplugin
    description:    |
        This [Composer](https://getcomposer.org/) plugin provides pluggable extensions.

plugins:
    hiqdev/hidev-php:           "*"
    hiqdev/hidev-vendor:        "*"
