package:
    type:           composer-plugin
    name:           composer-extension-plugin
    namespace:      hiqdev\composerextensionplugin
    headline:       Composer Extension Plugin
    title:          Composer plugin for Yii extensions
    forum:          http://forum.hiqdev.com/
    keywords:       composer, yii2, extension, plugin
    description:    |
        This [Composer](https://getcomposer.org/) plugin provides
        more functional Yii extensions.

require:
    hiqdev/hidev-php:    "*"
    hiqdev/hidev-vendor: "*"
